language: node_js
node_js:
  - 9
cache:
  directories:
    - webapp/node_modules
    - backend/node_modules
install:
  - cd webapp && npm install && cd ..
  - cd backend && npm install && cd ..

script:
  - npm run web:test
