language: node_js
node_js:
  - 9
cache:
  directories:
    - webapp/node_modules
    - backend/node_modules
services:
  - neo4j
install:
  - npm install
  - cd webapp && npm install && cd ..
  - cd backend && npm install && cd ..
before_script:
  - cd backend && npm run seed
script:
  - npm run web:lint
  - npm run web:test
  - npm run backend:lint
  - npm run backend:test
