language: node_js
node_js:
  - 9
cache:
  directories:
    - webapp/node_modules
    - backend/node_modules
env:
  - NEO4J_VERSION="3.5.14"
before_install:
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - neo4j-community-$NEO4J_VERSION/bin/neo4j-admin set-initial-password password
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start
install:
  - npm install
  - cd webapp && npm install && cd ..
  - cd backend && npm install && cd ..
before_script:
  - npm run backend:seed
script:
  - npm run web:lint
  - npm run web:test
  - npm run backend:lint
  - npm run backend:test
